// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: node.proto

package nodepbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	nodepb "github.com/bpprotocol/blockparty/node/internal/nodepb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeServiceName is the fully-qualified name of the NodeService service.
	NodeServiceName = "blockparty.node.v1.NodeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeServiceGetStatusProcedure is the fully-qualified name of the NodeService's GetStatus RPC.
	NodeServiceGetStatusProcedure = "/blockparty.node.v1.NodeService/GetStatus"
	// NodeServiceBootstrapWorldProcedure is the fully-qualified name of the NodeService's
	// BootstrapWorld RPC.
	NodeServiceBootstrapWorldProcedure = "/blockparty.node.v1.NodeService/BootstrapWorld"
	// NodeServiceUnlockKeystoreProcedure is the fully-qualified name of the NodeService's
	// UnlockKeystore RPC.
	NodeServiceUnlockKeystoreProcedure = "/blockparty.node.v1.NodeService/UnlockKeystore"
	// NodeServicePostTextProcedure is the fully-qualified name of the NodeService's PostText RPC.
	NodeServicePostTextProcedure = "/blockparty.node.v1.NodeService/PostText"
	// NodeServiceGetBlockProcedure is the fully-qualified name of the NodeService's GetBlock RPC.
	NodeServiceGetBlockProcedure = "/blockparty.node.v1.NodeService/GetBlock"
	// NodeServiceListBlocksProcedure is the fully-qualified name of the NodeService's ListBlocks RPC.
	NodeServiceListBlocksProcedure = "/blockparty.node.v1.NodeService/ListBlocks"
	// NodeServiceSubscribeBlocksProcedure is the fully-qualified name of the NodeService's
	// SubscribeBlocks RPC.
	NodeServiceSubscribeBlocksProcedure = "/blockparty.node.v1.NodeService/SubscribeBlocks"
	// NodeServiceGetIdentityProcedure is the fully-qualified name of the NodeService's GetIdentity RPC.
	NodeServiceGetIdentityProcedure = "/blockparty.node.v1.NodeService/GetIdentity"
	// NodeServiceAddPeerProcedure is the fully-qualified name of the NodeService's AddPeer RPC.
	NodeServiceAddPeerProcedure = "/blockparty.node.v1.NodeService/AddPeer"
	// NodeServiceStartConnectionProcedure is the fully-qualified name of the NodeService's
	// StartConnection RPC.
	NodeServiceStartConnectionProcedure = "/blockparty.node.v1.NodeService/StartConnection"
	// NodeServiceListConnectionsProcedure is the fully-qualified name of the NodeService's
	// ListConnections RPC.
	NodeServiceListConnectionsProcedure = "/blockparty.node.v1.NodeService/ListConnections"
	// NodeServiceRotateConnectionProcedure is the fully-qualified name of the NodeService's
	// RotateConnection RPC.
	NodeServiceRotateConnectionProcedure = "/blockparty.node.v1.NodeService/RotateConnection"
	// NodeServiceCloseConnectionProcedure is the fully-qualified name of the NodeService's
	// CloseConnection RPC.
	NodeServiceCloseConnectionProcedure = "/blockparty.node.v1.NodeService/CloseConnection"
	// NodeServiceSendPrivateTextProcedure is the fully-qualified name of the NodeService's
	// SendPrivateText RPC.
	NodeServiceSendPrivateTextProcedure = "/blockparty.node.v1.NodeService/SendPrivateText"
	// NodeServiceListConnectionMessagesProcedure is the fully-qualified name of the NodeService's
	// ListConnectionMessages RPC.
	NodeServiceListConnectionMessagesProcedure = "/blockparty.node.v1.NodeService/ListConnectionMessages"
	// NodeServiceRotateIdentityProcedure is the fully-qualified name of the NodeService's
	// RotateIdentity RPC.
	NodeServiceRotateIdentityProcedure = "/blockparty.node.v1.NodeService/RotateIdentity"
	// NodeServiceBurnIdentityProcedure is the fully-qualified name of the NodeService's BurnIdentity
	// RPC.
	NodeServiceBurnIdentityProcedure = "/blockparty.node.v1.NodeService/BurnIdentity"
)

// NodeServiceClient is a client for the blockparty.node.v1.NodeService service.
type NodeServiceClient interface {
	// GetStatus reports node mode, whether a World is loaded, the identity, and
	// the stored block count. Used by the client's onboarding flow (#26 Q5).
	GetStatus(context.Context, *connect.Request[nodepb.GetStatusRequest]) (*connect.Response[nodepb.GetStatusResponse], error)
	// BootstrapWorld configures the node's World at runtime when none is loaded
	// (personal mode only): it initializes the keystore from the supplied secrets.
	// Honors the single-World invariant.
	BootstrapWorld(context.Context, *connect.Request[nodepb.BootstrapWorldRequest]) (*connect.Response[nodepb.BootstrapWorldResponse], error)
	// UnlockKeystore unlocks an existing encrypted keystore at runtime, deriving
	// the World and identity in memory (personal mode, when a keystore is present
	// but no World is loaded). This is the client-driven alternative to handing
	// the node BPNODE_KEYSTORE_PASSPHRASE at startup: a node booted without it
	// reports keystore_exists=true and waits here.
	UnlockKeystore(context.Context, *connect.Request[nodepb.UnlockKeystoreRequest]) (*connect.Response[nodepb.UnlockKeystoreResponse], error)
	// PostText authors a content.post to a public audience. The client submits
	// intent (audience + text); the node encrypts and signs (world_sig+author_sig)
	// and stores it. The client never handles a private key.
	PostText(context.Context, *connect.Request[nodepb.PostTextRequest]) (*connect.Response[nodepb.PostTextResponse], error)
	// GetBlock fetches a stored block by ID, returning plaintext when the node can
	// open the audience (public audience in personal mode), ciphertext otherwise.
	GetBlock(context.Context, *connect.Request[nodepb.GetBlockRequest]) (*connect.Response[nodepb.GetBlockResponse], error)
	// ListBlocks queries the local index by audience, type, author, or time range.
	ListBlocks(context.Context, *connect.Request[nodepb.ListBlocksRequest]) (*connect.Response[nodepb.ListBlocksResponse], error)
	// SubscribeBlocks streams a BlockEvent for each block accepted onto an
	// audience after subscription — the live feed (#44). Pair with ListBlocks for
	// the initial backlog.
	SubscribeBlocks(context.Context, *connect.Request[nodepb.SubscribeBlocksRequest]) (*connect.ServerStreamForClient[nodepb.BlockEvent], error)
	// GetIdentity returns this node's connection card (address + public keys) to
	// share out-of-band so a peer can connect.
	GetIdentity(context.Context, *connect.Request[nodepb.GetIdentityRequest]) (*connect.Response[nodepb.GetIdentityResponse], error)
	// AddPeer registers a known peer's card so the node can connect to it and
	// recognize its handshake blocks.
	AddPeer(context.Context, *connect.Request[nodepb.AddPeerRequest]) (*connect.Response[nodepb.AddPeerResponse], error)
	// StartConnection initiates a connect.request handshake to a registered peer.
	StartConnection(context.Context, *connect.Request[nodepb.StartConnectionRequest]) (*connect.Response[nodepb.StartConnectionResponse], error)
	// ListConnections lists the node's active connections.
	ListConnections(context.Context, *connect.Request[nodepb.ListConnectionsRequest]) (*connect.Response[nodepb.ListConnectionsResponse], error)
	// RotateConnection advances a connection to a new epoch (re-keys the channel).
	RotateConnection(context.Context, *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ConnectionResult], error)
	// CloseConnection tears a connection down and notifies the peer.
	CloseConnection(context.Context, *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ConnectionResult], error)
	// SendPrivateText posts an encrypted message on a connection's private audience.
	SendPrivateText(context.Context, *connect.Request[nodepb.SendPrivateTextRequest]) (*connect.Response[nodepb.PostTextResponse], error)
	// ListConnectionMessages returns the decrypted messages on a connection's
	// current private audience.
	ListConnectionMessages(context.Context, *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ListConnectionMessagesResponse], error)
	// RotateIdentity replaces the identity passphrase, yielding a new identity.
	// Dangerous: requires confirm=true (the #29 confirmation gate).
	RotateIdentity(context.Context, *connect.Request[nodepb.RotateIdentityRequest]) (*connect.Response[nodepb.RotateIdentityResponse], error)
	// BurnIdentity authors and publishes an identity.burn revoking this identity.
	// Irreversible: requires confirm=true.
	BurnIdentity(context.Context, *connect.Request[nodepb.BurnIdentityRequest]) (*connect.Response[nodepb.BurnIdentityResponse], error)
}

// NewNodeServiceClient constructs a client for the blockparty.node.v1.NodeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nodeServiceMethods := nodepb.File_node_proto.Services().ByName("NodeService").Methods()
	return &nodeServiceClient{
		getStatus: connect.NewClient[nodepb.GetStatusRequest, nodepb.GetStatusResponse](
			httpClient,
			baseURL+NodeServiceGetStatusProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		bootstrapWorld: connect.NewClient[nodepb.BootstrapWorldRequest, nodepb.BootstrapWorldResponse](
			httpClient,
			baseURL+NodeServiceBootstrapWorldProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("BootstrapWorld")),
			connect.WithClientOptions(opts...),
		),
		unlockKeystore: connect.NewClient[nodepb.UnlockKeystoreRequest, nodepb.UnlockKeystoreResponse](
			httpClient,
			baseURL+NodeServiceUnlockKeystoreProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("UnlockKeystore")),
			connect.WithClientOptions(opts...),
		),
		postText: connect.NewClient[nodepb.PostTextRequest, nodepb.PostTextResponse](
			httpClient,
			baseURL+NodeServicePostTextProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("PostText")),
			connect.WithClientOptions(opts...),
		),
		getBlock: connect.NewClient[nodepb.GetBlockRequest, nodepb.GetBlockResponse](
			httpClient,
			baseURL+NodeServiceGetBlockProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetBlock")),
			connect.WithClientOptions(opts...),
		),
		listBlocks: connect.NewClient[nodepb.ListBlocksRequest, nodepb.ListBlocksResponse](
			httpClient,
			baseURL+NodeServiceListBlocksProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ListBlocks")),
			connect.WithClientOptions(opts...),
		),
		subscribeBlocks: connect.NewClient[nodepb.SubscribeBlocksRequest, nodepb.BlockEvent](
			httpClient,
			baseURL+NodeServiceSubscribeBlocksProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("SubscribeBlocks")),
			connect.WithClientOptions(opts...),
		),
		getIdentity: connect.NewClient[nodepb.GetIdentityRequest, nodepb.GetIdentityResponse](
			httpClient,
			baseURL+NodeServiceGetIdentityProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetIdentity")),
			connect.WithClientOptions(opts...),
		),
		addPeer: connect.NewClient[nodepb.AddPeerRequest, nodepb.AddPeerResponse](
			httpClient,
			baseURL+NodeServiceAddPeerProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("AddPeer")),
			connect.WithClientOptions(opts...),
		),
		startConnection: connect.NewClient[nodepb.StartConnectionRequest, nodepb.StartConnectionResponse](
			httpClient,
			baseURL+NodeServiceStartConnectionProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("StartConnection")),
			connect.WithClientOptions(opts...),
		),
		listConnections: connect.NewClient[nodepb.ListConnectionsRequest, nodepb.ListConnectionsResponse](
			httpClient,
			baseURL+NodeServiceListConnectionsProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ListConnections")),
			connect.WithClientOptions(opts...),
		),
		rotateConnection: connect.NewClient[nodepb.ConnectionRef, nodepb.ConnectionResult](
			httpClient,
			baseURL+NodeServiceRotateConnectionProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("RotateConnection")),
			connect.WithClientOptions(opts...),
		),
		closeConnection: connect.NewClient[nodepb.ConnectionRef, nodepb.ConnectionResult](
			httpClient,
			baseURL+NodeServiceCloseConnectionProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("CloseConnection")),
			connect.WithClientOptions(opts...),
		),
		sendPrivateText: connect.NewClient[nodepb.SendPrivateTextRequest, nodepb.PostTextResponse](
			httpClient,
			baseURL+NodeServiceSendPrivateTextProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("SendPrivateText")),
			connect.WithClientOptions(opts...),
		),
		listConnectionMessages: connect.NewClient[nodepb.ConnectionRef, nodepb.ListConnectionMessagesResponse](
			httpClient,
			baseURL+NodeServiceListConnectionMessagesProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ListConnectionMessages")),
			connect.WithClientOptions(opts...),
		),
		rotateIdentity: connect.NewClient[nodepb.RotateIdentityRequest, nodepb.RotateIdentityResponse](
			httpClient,
			baseURL+NodeServiceRotateIdentityProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("RotateIdentity")),
			connect.WithClientOptions(opts...),
		),
		burnIdentity: connect.NewClient[nodepb.BurnIdentityRequest, nodepb.BurnIdentityResponse](
			httpClient,
			baseURL+NodeServiceBurnIdentityProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("BurnIdentity")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeServiceClient implements NodeServiceClient.
type nodeServiceClient struct {
	getStatus              *connect.Client[nodepb.GetStatusRequest, nodepb.GetStatusResponse]
	bootstrapWorld         *connect.Client[nodepb.BootstrapWorldRequest, nodepb.BootstrapWorldResponse]
	unlockKeystore         *connect.Client[nodepb.UnlockKeystoreRequest, nodepb.UnlockKeystoreResponse]
	postText               *connect.Client[nodepb.PostTextRequest, nodepb.PostTextResponse]
	getBlock               *connect.Client[nodepb.GetBlockRequest, nodepb.GetBlockResponse]
	listBlocks             *connect.Client[nodepb.ListBlocksRequest, nodepb.ListBlocksResponse]
	subscribeBlocks        *connect.Client[nodepb.SubscribeBlocksRequest, nodepb.BlockEvent]
	getIdentity            *connect.Client[nodepb.GetIdentityRequest, nodepb.GetIdentityResponse]
	addPeer                *connect.Client[nodepb.AddPeerRequest, nodepb.AddPeerResponse]
	startConnection        *connect.Client[nodepb.StartConnectionRequest, nodepb.StartConnectionResponse]
	listConnections        *connect.Client[nodepb.ListConnectionsRequest, nodepb.ListConnectionsResponse]
	rotateConnection       *connect.Client[nodepb.ConnectionRef, nodepb.ConnectionResult]
	closeConnection        *connect.Client[nodepb.ConnectionRef, nodepb.ConnectionResult]
	sendPrivateText        *connect.Client[nodepb.SendPrivateTextRequest, nodepb.PostTextResponse]
	listConnectionMessages *connect.Client[nodepb.ConnectionRef, nodepb.ListConnectionMessagesResponse]
	rotateIdentity         *connect.Client[nodepb.RotateIdentityRequest, nodepb.RotateIdentityResponse]
	burnIdentity           *connect.Client[nodepb.BurnIdentityRequest, nodepb.BurnIdentityResponse]
}

// GetStatus calls blockparty.node.v1.NodeService.GetStatus.
func (c *nodeServiceClient) GetStatus(ctx context.Context, req *connect.Request[nodepb.GetStatusRequest]) (*connect.Response[nodepb.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// BootstrapWorld calls blockparty.node.v1.NodeService.BootstrapWorld.
func (c *nodeServiceClient) BootstrapWorld(ctx context.Context, req *connect.Request[nodepb.BootstrapWorldRequest]) (*connect.Response[nodepb.BootstrapWorldResponse], error) {
	return c.bootstrapWorld.CallUnary(ctx, req)
}

// UnlockKeystore calls blockparty.node.v1.NodeService.UnlockKeystore.
func (c *nodeServiceClient) UnlockKeystore(ctx context.Context, req *connect.Request[nodepb.UnlockKeystoreRequest]) (*connect.Response[nodepb.UnlockKeystoreResponse], error) {
	return c.unlockKeystore.CallUnary(ctx, req)
}

// PostText calls blockparty.node.v1.NodeService.PostText.
func (c *nodeServiceClient) PostText(ctx context.Context, req *connect.Request[nodepb.PostTextRequest]) (*connect.Response[nodepb.PostTextResponse], error) {
	return c.postText.CallUnary(ctx, req)
}

// GetBlock calls blockparty.node.v1.NodeService.GetBlock.
func (c *nodeServiceClient) GetBlock(ctx context.Context, req *connect.Request[nodepb.GetBlockRequest]) (*connect.Response[nodepb.GetBlockResponse], error) {
	return c.getBlock.CallUnary(ctx, req)
}

// ListBlocks calls blockparty.node.v1.NodeService.ListBlocks.
func (c *nodeServiceClient) ListBlocks(ctx context.Context, req *connect.Request[nodepb.ListBlocksRequest]) (*connect.Response[nodepb.ListBlocksResponse], error) {
	return c.listBlocks.CallUnary(ctx, req)
}

// SubscribeBlocks calls blockparty.node.v1.NodeService.SubscribeBlocks.
func (c *nodeServiceClient) SubscribeBlocks(ctx context.Context, req *connect.Request[nodepb.SubscribeBlocksRequest]) (*connect.ServerStreamForClient[nodepb.BlockEvent], error) {
	return c.subscribeBlocks.CallServerStream(ctx, req)
}

// GetIdentity calls blockparty.node.v1.NodeService.GetIdentity.
func (c *nodeServiceClient) GetIdentity(ctx context.Context, req *connect.Request[nodepb.GetIdentityRequest]) (*connect.Response[nodepb.GetIdentityResponse], error) {
	return c.getIdentity.CallUnary(ctx, req)
}

// AddPeer calls blockparty.node.v1.NodeService.AddPeer.
func (c *nodeServiceClient) AddPeer(ctx context.Context, req *connect.Request[nodepb.AddPeerRequest]) (*connect.Response[nodepb.AddPeerResponse], error) {
	return c.addPeer.CallUnary(ctx, req)
}

// StartConnection calls blockparty.node.v1.NodeService.StartConnection.
func (c *nodeServiceClient) StartConnection(ctx context.Context, req *connect.Request[nodepb.StartConnectionRequest]) (*connect.Response[nodepb.StartConnectionResponse], error) {
	return c.startConnection.CallUnary(ctx, req)
}

// ListConnections calls blockparty.node.v1.NodeService.ListConnections.
func (c *nodeServiceClient) ListConnections(ctx context.Context, req *connect.Request[nodepb.ListConnectionsRequest]) (*connect.Response[nodepb.ListConnectionsResponse], error) {
	return c.listConnections.CallUnary(ctx, req)
}

// RotateConnection calls blockparty.node.v1.NodeService.RotateConnection.
func (c *nodeServiceClient) RotateConnection(ctx context.Context, req *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ConnectionResult], error) {
	return c.rotateConnection.CallUnary(ctx, req)
}

// CloseConnection calls blockparty.node.v1.NodeService.CloseConnection.
func (c *nodeServiceClient) CloseConnection(ctx context.Context, req *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ConnectionResult], error) {
	return c.closeConnection.CallUnary(ctx, req)
}

// SendPrivateText calls blockparty.node.v1.NodeService.SendPrivateText.
func (c *nodeServiceClient) SendPrivateText(ctx context.Context, req *connect.Request[nodepb.SendPrivateTextRequest]) (*connect.Response[nodepb.PostTextResponse], error) {
	return c.sendPrivateText.CallUnary(ctx, req)
}

// ListConnectionMessages calls blockparty.node.v1.NodeService.ListConnectionMessages.
func (c *nodeServiceClient) ListConnectionMessages(ctx context.Context, req *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ListConnectionMessagesResponse], error) {
	return c.listConnectionMessages.CallUnary(ctx, req)
}

// RotateIdentity calls blockparty.node.v1.NodeService.RotateIdentity.
func (c *nodeServiceClient) RotateIdentity(ctx context.Context, req *connect.Request[nodepb.RotateIdentityRequest]) (*connect.Response[nodepb.RotateIdentityResponse], error) {
	return c.rotateIdentity.CallUnary(ctx, req)
}

// BurnIdentity calls blockparty.node.v1.NodeService.BurnIdentity.
func (c *nodeServiceClient) BurnIdentity(ctx context.Context, req *connect.Request[nodepb.BurnIdentityRequest]) (*connect.Response[nodepb.BurnIdentityResponse], error) {
	return c.burnIdentity.CallUnary(ctx, req)
}

// NodeServiceHandler is an implementation of the blockparty.node.v1.NodeService service.
type NodeServiceHandler interface {
	// GetStatus reports node mode, whether a World is loaded, the identity, and
	// the stored block count. Used by the client's onboarding flow (#26 Q5).
	GetStatus(context.Context, *connect.Request[nodepb.GetStatusRequest]) (*connect.Response[nodepb.GetStatusResponse], error)
	// BootstrapWorld configures the node's World at runtime when none is loaded
	// (personal mode only): it initializes the keystore from the supplied secrets.
	// Honors the single-World invariant.
	BootstrapWorld(context.Context, *connect.Request[nodepb.BootstrapWorldRequest]) (*connect.Response[nodepb.BootstrapWorldResponse], error)
	// UnlockKeystore unlocks an existing encrypted keystore at runtime, deriving
	// the World and identity in memory (personal mode, when a keystore is present
	// but no World is loaded). This is the client-driven alternative to handing
	// the node BPNODE_KEYSTORE_PASSPHRASE at startup: a node booted without it
	// reports keystore_exists=true and waits here.
	UnlockKeystore(context.Context, *connect.Request[nodepb.UnlockKeystoreRequest]) (*connect.Response[nodepb.UnlockKeystoreResponse], error)
	// PostText authors a content.post to a public audience. The client submits
	// intent (audience + text); the node encrypts and signs (world_sig+author_sig)
	// and stores it. The client never handles a private key.
	PostText(context.Context, *connect.Request[nodepb.PostTextRequest]) (*connect.Response[nodepb.PostTextResponse], error)
	// GetBlock fetches a stored block by ID, returning plaintext when the node can
	// open the audience (public audience in personal mode), ciphertext otherwise.
	GetBlock(context.Context, *connect.Request[nodepb.GetBlockRequest]) (*connect.Response[nodepb.GetBlockResponse], error)
	// ListBlocks queries the local index by audience, type, author, or time range.
	ListBlocks(context.Context, *connect.Request[nodepb.ListBlocksRequest]) (*connect.Response[nodepb.ListBlocksResponse], error)
	// SubscribeBlocks streams a BlockEvent for each block accepted onto an
	// audience after subscription — the live feed (#44). Pair with ListBlocks for
	// the initial backlog.
	SubscribeBlocks(context.Context, *connect.Request[nodepb.SubscribeBlocksRequest], *connect.ServerStream[nodepb.BlockEvent]) error
	// GetIdentity returns this node's connection card (address + public keys) to
	// share out-of-band so a peer can connect.
	GetIdentity(context.Context, *connect.Request[nodepb.GetIdentityRequest]) (*connect.Response[nodepb.GetIdentityResponse], error)
	// AddPeer registers a known peer's card so the node can connect to it and
	// recognize its handshake blocks.
	AddPeer(context.Context, *connect.Request[nodepb.AddPeerRequest]) (*connect.Response[nodepb.AddPeerResponse], error)
	// StartConnection initiates a connect.request handshake to a registered peer.
	StartConnection(context.Context, *connect.Request[nodepb.StartConnectionRequest]) (*connect.Response[nodepb.StartConnectionResponse], error)
	// ListConnections lists the node's active connections.
	ListConnections(context.Context, *connect.Request[nodepb.ListConnectionsRequest]) (*connect.Response[nodepb.ListConnectionsResponse], error)
	// RotateConnection advances a connection to a new epoch (re-keys the channel).
	RotateConnection(context.Context, *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ConnectionResult], error)
	// CloseConnection tears a connection down and notifies the peer.
	CloseConnection(context.Context, *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ConnectionResult], error)
	// SendPrivateText posts an encrypted message on a connection's private audience.
	SendPrivateText(context.Context, *connect.Request[nodepb.SendPrivateTextRequest]) (*connect.Response[nodepb.PostTextResponse], error)
	// ListConnectionMessages returns the decrypted messages on a connection's
	// current private audience.
	ListConnectionMessages(context.Context, *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ListConnectionMessagesResponse], error)
	// RotateIdentity replaces the identity passphrase, yielding a new identity.
	// Dangerous: requires confirm=true (the #29 confirmation gate).
	RotateIdentity(context.Context, *connect.Request[nodepb.RotateIdentityRequest]) (*connect.Response[nodepb.RotateIdentityResponse], error)
	// BurnIdentity authors and publishes an identity.burn revoking this identity.
	// Irreversible: requires confirm=true.
	BurnIdentity(context.Context, *connect.Request[nodepb.BurnIdentityRequest]) (*connect.Response[nodepb.BurnIdentityResponse], error)
}

// NewNodeServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeServiceHandler(svc NodeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeServiceMethods := nodepb.File_node_proto.Services().ByName("NodeService").Methods()
	nodeServiceGetStatusHandler := connect.NewUnaryHandler(
		NodeServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(nodeServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceBootstrapWorldHandler := connect.NewUnaryHandler(
		NodeServiceBootstrapWorldProcedure,
		svc.BootstrapWorld,
		connect.WithSchema(nodeServiceMethods.ByName("BootstrapWorld")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceUnlockKeystoreHandler := connect.NewUnaryHandler(
		NodeServiceUnlockKeystoreProcedure,
		svc.UnlockKeystore,
		connect.WithSchema(nodeServiceMethods.ByName("UnlockKeystore")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServicePostTextHandler := connect.NewUnaryHandler(
		NodeServicePostTextProcedure,
		svc.PostText,
		connect.WithSchema(nodeServiceMethods.ByName("PostText")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceGetBlockHandler := connect.NewUnaryHandler(
		NodeServiceGetBlockProcedure,
		svc.GetBlock,
		connect.WithSchema(nodeServiceMethods.ByName("GetBlock")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceListBlocksHandler := connect.NewUnaryHandler(
		NodeServiceListBlocksProcedure,
		svc.ListBlocks,
		connect.WithSchema(nodeServiceMethods.ByName("ListBlocks")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceSubscribeBlocksHandler := connect.NewServerStreamHandler(
		NodeServiceSubscribeBlocksProcedure,
		svc.SubscribeBlocks,
		connect.WithSchema(nodeServiceMethods.ByName("SubscribeBlocks")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceGetIdentityHandler := connect.NewUnaryHandler(
		NodeServiceGetIdentityProcedure,
		svc.GetIdentity,
		connect.WithSchema(nodeServiceMethods.ByName("GetIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceAddPeerHandler := connect.NewUnaryHandler(
		NodeServiceAddPeerProcedure,
		svc.AddPeer,
		connect.WithSchema(nodeServiceMethods.ByName("AddPeer")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceStartConnectionHandler := connect.NewUnaryHandler(
		NodeServiceStartConnectionProcedure,
		svc.StartConnection,
		connect.WithSchema(nodeServiceMethods.ByName("StartConnection")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceListConnectionsHandler := connect.NewUnaryHandler(
		NodeServiceListConnectionsProcedure,
		svc.ListConnections,
		connect.WithSchema(nodeServiceMethods.ByName("ListConnections")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceRotateConnectionHandler := connect.NewUnaryHandler(
		NodeServiceRotateConnectionProcedure,
		svc.RotateConnection,
		connect.WithSchema(nodeServiceMethods.ByName("RotateConnection")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceCloseConnectionHandler := connect.NewUnaryHandler(
		NodeServiceCloseConnectionProcedure,
		svc.CloseConnection,
		connect.WithSchema(nodeServiceMethods.ByName("CloseConnection")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceSendPrivateTextHandler := connect.NewUnaryHandler(
		NodeServiceSendPrivateTextProcedure,
		svc.SendPrivateText,
		connect.WithSchema(nodeServiceMethods.ByName("SendPrivateText")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceListConnectionMessagesHandler := connect.NewUnaryHandler(
		NodeServiceListConnectionMessagesProcedure,
		svc.ListConnectionMessages,
		connect.WithSchema(nodeServiceMethods.ByName("ListConnectionMessages")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceRotateIdentityHandler := connect.NewUnaryHandler(
		NodeServiceRotateIdentityProcedure,
		svc.RotateIdentity,
		connect.WithSchema(nodeServiceMethods.ByName("RotateIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceBurnIdentityHandler := connect.NewUnaryHandler(
		NodeServiceBurnIdentityProcedure,
		svc.BurnIdentity,
		connect.WithSchema(nodeServiceMethods.ByName("BurnIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	return "/blockparty.node.v1.NodeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeServiceGetStatusProcedure:
			nodeServiceGetStatusHandler.ServeHTTP(w, r)
		case NodeServiceBootstrapWorldProcedure:
			nodeServiceBootstrapWorldHandler.ServeHTTP(w, r)
		case NodeServiceUnlockKeystoreProcedure:
			nodeServiceUnlockKeystoreHandler.ServeHTTP(w, r)
		case NodeServicePostTextProcedure:
			nodeServicePostTextHandler.ServeHTTP(w, r)
		case NodeServiceGetBlockProcedure:
			nodeServiceGetBlockHandler.ServeHTTP(w, r)
		case NodeServiceListBlocksProcedure:
			nodeServiceListBlocksHandler.ServeHTTP(w, r)
		case NodeServiceSubscribeBlocksProcedure:
			nodeServiceSubscribeBlocksHandler.ServeHTTP(w, r)
		case NodeServiceGetIdentityProcedure:
			nodeServiceGetIdentityHandler.ServeHTTP(w, r)
		case NodeServiceAddPeerProcedure:
			nodeServiceAddPeerHandler.ServeHTTP(w, r)
		case NodeServiceStartConnectionProcedure:
			nodeServiceStartConnectionHandler.ServeHTTP(w, r)
		case NodeServiceListConnectionsProcedure:
			nodeServiceListConnectionsHandler.ServeHTTP(w, r)
		case NodeServiceRotateConnectionProcedure:
			nodeServiceRotateConnectionHandler.ServeHTTP(w, r)
		case NodeServiceCloseConnectionProcedure:
			nodeServiceCloseConnectionHandler.ServeHTTP(w, r)
		case NodeServiceSendPrivateTextProcedure:
			nodeServiceSendPrivateTextHandler.ServeHTTP(w, r)
		case NodeServiceListConnectionMessagesProcedure:
			nodeServiceListConnectionMessagesHandler.ServeHTTP(w, r)
		case NodeServiceRotateIdentityProcedure:
			nodeServiceRotateIdentityHandler.ServeHTTP(w, r)
		case NodeServiceBurnIdentityProcedure:
			nodeServiceBurnIdentityHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeServiceHandler struct{}

func (UnimplementedNodeServiceHandler) GetStatus(context.Context, *connect.Request[nodepb.GetStatusRequest]) (*connect.Response[nodepb.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.GetStatus is not implemented"))
}

func (UnimplementedNodeServiceHandler) BootstrapWorld(context.Context, *connect.Request[nodepb.BootstrapWorldRequest]) (*connect.Response[nodepb.BootstrapWorldResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.BootstrapWorld is not implemented"))
}

func (UnimplementedNodeServiceHandler) UnlockKeystore(context.Context, *connect.Request[nodepb.UnlockKeystoreRequest]) (*connect.Response[nodepb.UnlockKeystoreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.UnlockKeystore is not implemented"))
}

func (UnimplementedNodeServiceHandler) PostText(context.Context, *connect.Request[nodepb.PostTextRequest]) (*connect.Response[nodepb.PostTextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.PostText is not implemented"))
}

func (UnimplementedNodeServiceHandler) GetBlock(context.Context, *connect.Request[nodepb.GetBlockRequest]) (*connect.Response[nodepb.GetBlockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.GetBlock is not implemented"))
}

func (UnimplementedNodeServiceHandler) ListBlocks(context.Context, *connect.Request[nodepb.ListBlocksRequest]) (*connect.Response[nodepb.ListBlocksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.ListBlocks is not implemented"))
}

func (UnimplementedNodeServiceHandler) SubscribeBlocks(context.Context, *connect.Request[nodepb.SubscribeBlocksRequest], *connect.ServerStream[nodepb.BlockEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.SubscribeBlocks is not implemented"))
}

func (UnimplementedNodeServiceHandler) GetIdentity(context.Context, *connect.Request[nodepb.GetIdentityRequest]) (*connect.Response[nodepb.GetIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.GetIdentity is not implemented"))
}

func (UnimplementedNodeServiceHandler) AddPeer(context.Context, *connect.Request[nodepb.AddPeerRequest]) (*connect.Response[nodepb.AddPeerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.AddPeer is not implemented"))
}

func (UnimplementedNodeServiceHandler) StartConnection(context.Context, *connect.Request[nodepb.StartConnectionRequest]) (*connect.Response[nodepb.StartConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.StartConnection is not implemented"))
}

func (UnimplementedNodeServiceHandler) ListConnections(context.Context, *connect.Request[nodepb.ListConnectionsRequest]) (*connect.Response[nodepb.ListConnectionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.ListConnections is not implemented"))
}

func (UnimplementedNodeServiceHandler) RotateConnection(context.Context, *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ConnectionResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.RotateConnection is not implemented"))
}

func (UnimplementedNodeServiceHandler) CloseConnection(context.Context, *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ConnectionResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.CloseConnection is not implemented"))
}

func (UnimplementedNodeServiceHandler) SendPrivateText(context.Context, *connect.Request[nodepb.SendPrivateTextRequest]) (*connect.Response[nodepb.PostTextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.SendPrivateText is not implemented"))
}

func (UnimplementedNodeServiceHandler) ListConnectionMessages(context.Context, *connect.Request[nodepb.ConnectionRef]) (*connect.Response[nodepb.ListConnectionMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.ListConnectionMessages is not implemented"))
}

func (UnimplementedNodeServiceHandler) RotateIdentity(context.Context, *connect.Request[nodepb.RotateIdentityRequest]) (*connect.Response[nodepb.RotateIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.RotateIdentity is not implemented"))
}

func (UnimplementedNodeServiceHandler) BurnIdentity(context.Context, *connect.Request[nodepb.BurnIdentityRequest]) (*connect.Response[nodepb.BurnIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.BurnIdentity is not implemented"))
}
