// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: node.proto

package nodepbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	nodepb "github.com/bpprotocol/blockparty/node/internal/nodepb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeServiceName is the fully-qualified name of the NodeService service.
	NodeServiceName = "blockparty.node.v1.NodeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeServiceGetStatusProcedure is the fully-qualified name of the NodeService's GetStatus RPC.
	NodeServiceGetStatusProcedure = "/blockparty.node.v1.NodeService/GetStatus"
	// NodeServiceBootstrapWorldProcedure is the fully-qualified name of the NodeService's
	// BootstrapWorld RPC.
	NodeServiceBootstrapWorldProcedure = "/blockparty.node.v1.NodeService/BootstrapWorld"
	// NodeServicePostTextProcedure is the fully-qualified name of the NodeService's PostText RPC.
	NodeServicePostTextProcedure = "/blockparty.node.v1.NodeService/PostText"
	// NodeServiceGetBlockProcedure is the fully-qualified name of the NodeService's GetBlock RPC.
	NodeServiceGetBlockProcedure = "/blockparty.node.v1.NodeService/GetBlock"
	// NodeServiceListBlocksProcedure is the fully-qualified name of the NodeService's ListBlocks RPC.
	NodeServiceListBlocksProcedure = "/blockparty.node.v1.NodeService/ListBlocks"
)

// NodeServiceClient is a client for the blockparty.node.v1.NodeService service.
type NodeServiceClient interface {
	// GetStatus reports node mode, whether a World is loaded, the identity, and
	// the stored block count. Used by the client's onboarding flow (#26 Q5).
	GetStatus(context.Context, *connect.Request[nodepb.GetStatusRequest]) (*connect.Response[nodepb.GetStatusResponse], error)
	// BootstrapWorld configures the node's World at runtime when none is loaded
	// (personal mode only): it initializes the keystore from the supplied secrets.
	// Honors the single-World invariant.
	BootstrapWorld(context.Context, *connect.Request[nodepb.BootstrapWorldRequest]) (*connect.Response[nodepb.BootstrapWorldResponse], error)
	// PostText authors a content.post to a public audience. The client submits
	// intent (audience + text); the node encrypts and signs (world_sig+author_sig)
	// and stores it. The client never handles a private key.
	PostText(context.Context, *connect.Request[nodepb.PostTextRequest]) (*connect.Response[nodepb.PostTextResponse], error)
	// GetBlock fetches a stored block by ID, returning plaintext when the node can
	// open the audience (public audience in personal mode), ciphertext otherwise.
	GetBlock(context.Context, *connect.Request[nodepb.GetBlockRequest]) (*connect.Response[nodepb.GetBlockResponse], error)
	// ListBlocks queries the local index by audience, type, author, or time range.
	ListBlocks(context.Context, *connect.Request[nodepb.ListBlocksRequest]) (*connect.Response[nodepb.ListBlocksResponse], error)
}

// NewNodeServiceClient constructs a client for the blockparty.node.v1.NodeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nodeServiceMethods := nodepb.File_node_proto.Services().ByName("NodeService").Methods()
	return &nodeServiceClient{
		getStatus: connect.NewClient[nodepb.GetStatusRequest, nodepb.GetStatusResponse](
			httpClient,
			baseURL+NodeServiceGetStatusProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		bootstrapWorld: connect.NewClient[nodepb.BootstrapWorldRequest, nodepb.BootstrapWorldResponse](
			httpClient,
			baseURL+NodeServiceBootstrapWorldProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("BootstrapWorld")),
			connect.WithClientOptions(opts...),
		),
		postText: connect.NewClient[nodepb.PostTextRequest, nodepb.PostTextResponse](
			httpClient,
			baseURL+NodeServicePostTextProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("PostText")),
			connect.WithClientOptions(opts...),
		),
		getBlock: connect.NewClient[nodepb.GetBlockRequest, nodepb.GetBlockResponse](
			httpClient,
			baseURL+NodeServiceGetBlockProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetBlock")),
			connect.WithClientOptions(opts...),
		),
		listBlocks: connect.NewClient[nodepb.ListBlocksRequest, nodepb.ListBlocksResponse](
			httpClient,
			baseURL+NodeServiceListBlocksProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ListBlocks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeServiceClient implements NodeServiceClient.
type nodeServiceClient struct {
	getStatus      *connect.Client[nodepb.GetStatusRequest, nodepb.GetStatusResponse]
	bootstrapWorld *connect.Client[nodepb.BootstrapWorldRequest, nodepb.BootstrapWorldResponse]
	postText       *connect.Client[nodepb.PostTextRequest, nodepb.PostTextResponse]
	getBlock       *connect.Client[nodepb.GetBlockRequest, nodepb.GetBlockResponse]
	listBlocks     *connect.Client[nodepb.ListBlocksRequest, nodepb.ListBlocksResponse]
}

// GetStatus calls blockparty.node.v1.NodeService.GetStatus.
func (c *nodeServiceClient) GetStatus(ctx context.Context, req *connect.Request[nodepb.GetStatusRequest]) (*connect.Response[nodepb.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// BootstrapWorld calls blockparty.node.v1.NodeService.BootstrapWorld.
func (c *nodeServiceClient) BootstrapWorld(ctx context.Context, req *connect.Request[nodepb.BootstrapWorldRequest]) (*connect.Response[nodepb.BootstrapWorldResponse], error) {
	return c.bootstrapWorld.CallUnary(ctx, req)
}

// PostText calls blockparty.node.v1.NodeService.PostText.
func (c *nodeServiceClient) PostText(ctx context.Context, req *connect.Request[nodepb.PostTextRequest]) (*connect.Response[nodepb.PostTextResponse], error) {
	return c.postText.CallUnary(ctx, req)
}

// GetBlock calls blockparty.node.v1.NodeService.GetBlock.
func (c *nodeServiceClient) GetBlock(ctx context.Context, req *connect.Request[nodepb.GetBlockRequest]) (*connect.Response[nodepb.GetBlockResponse], error) {
	return c.getBlock.CallUnary(ctx, req)
}

// ListBlocks calls blockparty.node.v1.NodeService.ListBlocks.
func (c *nodeServiceClient) ListBlocks(ctx context.Context, req *connect.Request[nodepb.ListBlocksRequest]) (*connect.Response[nodepb.ListBlocksResponse], error) {
	return c.listBlocks.CallUnary(ctx, req)
}

// NodeServiceHandler is an implementation of the blockparty.node.v1.NodeService service.
type NodeServiceHandler interface {
	// GetStatus reports node mode, whether a World is loaded, the identity, and
	// the stored block count. Used by the client's onboarding flow (#26 Q5).
	GetStatus(context.Context, *connect.Request[nodepb.GetStatusRequest]) (*connect.Response[nodepb.GetStatusResponse], error)
	// BootstrapWorld configures the node's World at runtime when none is loaded
	// (personal mode only): it initializes the keystore from the supplied secrets.
	// Honors the single-World invariant.
	BootstrapWorld(context.Context, *connect.Request[nodepb.BootstrapWorldRequest]) (*connect.Response[nodepb.BootstrapWorldResponse], error)
	// PostText authors a content.post to a public audience. The client submits
	// intent (audience + text); the node encrypts and signs (world_sig+author_sig)
	// and stores it. The client never handles a private key.
	PostText(context.Context, *connect.Request[nodepb.PostTextRequest]) (*connect.Response[nodepb.PostTextResponse], error)
	// GetBlock fetches a stored block by ID, returning plaintext when the node can
	// open the audience (public audience in personal mode), ciphertext otherwise.
	GetBlock(context.Context, *connect.Request[nodepb.GetBlockRequest]) (*connect.Response[nodepb.GetBlockResponse], error)
	// ListBlocks queries the local index by audience, type, author, or time range.
	ListBlocks(context.Context, *connect.Request[nodepb.ListBlocksRequest]) (*connect.Response[nodepb.ListBlocksResponse], error)
}

// NewNodeServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeServiceHandler(svc NodeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeServiceMethods := nodepb.File_node_proto.Services().ByName("NodeService").Methods()
	nodeServiceGetStatusHandler := connect.NewUnaryHandler(
		NodeServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(nodeServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceBootstrapWorldHandler := connect.NewUnaryHandler(
		NodeServiceBootstrapWorldProcedure,
		svc.BootstrapWorld,
		connect.WithSchema(nodeServiceMethods.ByName("BootstrapWorld")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServicePostTextHandler := connect.NewUnaryHandler(
		NodeServicePostTextProcedure,
		svc.PostText,
		connect.WithSchema(nodeServiceMethods.ByName("PostText")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceGetBlockHandler := connect.NewUnaryHandler(
		NodeServiceGetBlockProcedure,
		svc.GetBlock,
		connect.WithSchema(nodeServiceMethods.ByName("GetBlock")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceListBlocksHandler := connect.NewUnaryHandler(
		NodeServiceListBlocksProcedure,
		svc.ListBlocks,
		connect.WithSchema(nodeServiceMethods.ByName("ListBlocks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/blockparty.node.v1.NodeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeServiceGetStatusProcedure:
			nodeServiceGetStatusHandler.ServeHTTP(w, r)
		case NodeServiceBootstrapWorldProcedure:
			nodeServiceBootstrapWorldHandler.ServeHTTP(w, r)
		case NodeServicePostTextProcedure:
			nodeServicePostTextHandler.ServeHTTP(w, r)
		case NodeServiceGetBlockProcedure:
			nodeServiceGetBlockHandler.ServeHTTP(w, r)
		case NodeServiceListBlocksProcedure:
			nodeServiceListBlocksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeServiceHandler struct{}

func (UnimplementedNodeServiceHandler) GetStatus(context.Context, *connect.Request[nodepb.GetStatusRequest]) (*connect.Response[nodepb.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.GetStatus is not implemented"))
}

func (UnimplementedNodeServiceHandler) BootstrapWorld(context.Context, *connect.Request[nodepb.BootstrapWorldRequest]) (*connect.Response[nodepb.BootstrapWorldResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.BootstrapWorld is not implemented"))
}

func (UnimplementedNodeServiceHandler) PostText(context.Context, *connect.Request[nodepb.PostTextRequest]) (*connect.Response[nodepb.PostTextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.PostText is not implemented"))
}

func (UnimplementedNodeServiceHandler) GetBlock(context.Context, *connect.Request[nodepb.GetBlockRequest]) (*connect.Response[nodepb.GetBlockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.GetBlock is not implemented"))
}

func (UnimplementedNodeServiceHandler) ListBlocks(context.Context, *connect.Request[nodepb.ListBlocksRequest]) (*connect.Response[nodepb.ListBlocksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blockparty.node.v1.NodeService.ListBlocks is not implemented"))
}
