// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: exchange.proto

package exchangepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Want struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           [][]byte               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`                            // block IDs (32 bytes each) the requester wants
	HaveOnly      bool                   `protobuf:"varint,2,opt,name=have_only,json=haveOnly,proto3" json:"have_only,omitempty"` // if true, respond with availability only (no block bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Want) Reset() {
	*x = Want{}
	mi := &file_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Want) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Want) ProtoMessage() {}

func (x *Want) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Want.ProtoReflect.Descriptor instead.
func (*Want) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *Want) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Want) GetHaveOnly() bool {
	if x != nil {
		return x.HaveOnly
	}
	return false
}

type BlockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Block         []byte                 `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"` // canonical block bytes (empty when have_only or absent)
	Have          bool                   `protobuf:"varint,3,opt,name=have,proto3" json:"have,omitempty"`  // the responder has this block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockItem) Reset() {
	*x = BlockItem{}
	mi := &file_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockItem) ProtoMessage() {}

func (x *BlockItem) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockItem.ProtoReflect.Descriptor instead.
func (*BlockItem) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *BlockItem) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BlockItem) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockItem) GetHave() bool {
	if x != nil {
		return x.Have
	}
	return false
}

type WantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BlockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WantResponse) Reset() {
	*x = WantResponse{}
	mi := &file_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantResponse) ProtoMessage() {}

func (x *WantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantResponse.ProtoReflect.Descriptor instead.
func (*WantResponse) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *WantResponse) GetItems() []*BlockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Digest asks a peer for the block IDs it holds for an audience — the "who has
// what" query that drives anti-entropy reconciliation (#36).
type Digest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudienceCode  []byte                 `protobuf:"bytes,1,opt,name=audience_code,json=audienceCode,proto3" json:"audience_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Digest) Reset() {
	*x = Digest{}
	mi := &file_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Digest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digest) ProtoMessage() {}

func (x *Digest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digest.ProtoReflect.Descriptor instead.
func (*Digest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *Digest) GetAudienceCode() []byte {
	if x != nil {
		return x.AudienceCode
	}
	return nil
}

type DigestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           [][]byte               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"` // block IDs the responder holds for the audience
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestResponse) Reset() {
	*x = DigestResponse{}
	mi := &file_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestResponse) ProtoMessage() {}

func (x *DigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestResponse.ProtoReflect.Descriptor instead.
func (*DigestResponse) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *DigestResponse) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_exchange_proto protoreflect.FileDescriptor

const file_exchange_proto_rawDesc = "" +
	"\n" +
	"\x0eexchange.proto\x12\x12blockparty.node.v1\"5\n" +
	"\x04Want\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\fR\x03ids\x12\x1b\n" +
	"\thave_only\x18\x02 \x01(\bR\bhaveOnly\"E\n" +
	"\tBlockItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05block\x18\x02 \x01(\fR\x05block\x12\x12\n" +
	"\x04have\x18\x03 \x01(\bR\x04have\"C\n" +
	"\fWantResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.blockparty.node.v1.BlockItemR\x05items\"-\n" +
	"\x06Digest\x12#\n" +
	"\raudience_code\x18\x01 \x01(\fR\faudienceCode\"\"\n" +
	"\x0eDigestResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\fR\x03idsBFZDgithub.com/bpprotocol/blockparty/node/internal/exchangepb;exchangepbb\x06proto3"

var (
	file_exchange_proto_rawDescOnce sync.Once
	file_exchange_proto_rawDescData []byte
)

func file_exchange_proto_rawDescGZIP() []byte {
	file_exchange_proto_rawDescOnce.Do(func() {
		file_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_proto_rawDesc), len(file_exchange_proto_rawDesc)))
	})
	return file_exchange_proto_rawDescData
}

var file_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_exchange_proto_goTypes = []any{
	(*Want)(nil),           // 0: blockparty.node.v1.Want
	(*BlockItem)(nil),      // 1: blockparty.node.v1.BlockItem
	(*WantResponse)(nil),   // 2: blockparty.node.v1.WantResponse
	(*Digest)(nil),         // 3: blockparty.node.v1.Digest
	(*DigestResponse)(nil), // 4: blockparty.node.v1.DigestResponse
}
var file_exchange_proto_depIdxs = []int32{
	1, // 0: blockparty.node.v1.WantResponse.items:type_name -> blockparty.node.v1.BlockItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exchange_proto_init() }
func file_exchange_proto_init() {
	if File_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_proto_rawDesc), len(file_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exchange_proto_goTypes,
		DependencyIndexes: file_exchange_proto_depIdxs,
		MessageInfos:      file_exchange_proto_msgTypes,
	}.Build()
	File_exchange_proto = out.File
	file_exchange_proto_goTypes = nil
	file_exchange_proto_depIdxs = nil
}
