// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file block.proto (package blockparty.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file block.proto.
 */
export const file_block: GenFile = /*@__PURE__*/
  fileDesc("CgtibG9jay5wcm90bxINYmxvY2twYXJ0eS52MSKYAQoFQmxvY2sSDwoHdmVyc2lvbhgBIAEoDRIKCgJpZBgCIAEoDBIRCgl0eXBlX2NvZGUYAyABKAwSFQoNYXVkaWVuY2VfY29kZRgEIAEoDBIRCgl0aW1lc3RhbXAYBSABKAMSDAoEZGF0YRgGIAEoDBInCgRzaWdzGAcgASgLMhkuYmxvY2twYXJ0eS52MS5TaWduYXR1cmVzIlkKClNpZ25hdHVyZXMSDQoFd29ybGQYASABKAwSDgoGYXV0aG9yGAIgASgMEiwKBWV4dHJhGAMgAygLMh0uYmxvY2twYXJ0eS52MS5FeHRyYVNpZ25hdHVyZSIrCg5FeHRyYVNpZ25hdHVyZRIMCgR0eXBlGAEgASgJEgsKA3NpZxgCIAEoDEI2WjRnaXRodWIuY29tL2JwcHJvdG9jb2wvYmxvY2twYXJ0eS9zZGsvYmxvY2twYjtibG9ja3BiYgZwcm90bzM");

/**
 * Canonical BlockParty block format
 *
 * @generated from message blockparty.v1.Block
 */
export type Block = Message<"blockparty.v1.Block"> & {
  /**
   * Block version (e.g. 1)
   *
   * @generated from field: uint32 version = 1;
   */
  version: number;

  /**
   * Derived block ID (optional precomputed or recomputed)
   *
   * @generated from field: bytes id = 2;
   */
  id: Uint8Array;

  /**
   * World-scoped type hash
   *
   * @generated from field: bytes type_code = 3;
   */
  typeCode: Uint8Array;

  /**
   * World-scoped audience hash
   *
   * @generated from field: bytes audience_code = 4;
   */
  audienceCode: Uint8Array;

  /**
   * Unix timestamp (seconds since epoch)
   *
   * @generated from field: int64 timestamp = 5;
   */
  timestamp: bigint;

  /**
   * Encrypted or plaintext payload
   *
   * @generated from field: bytes data = 6;
   */
  data: Uint8Array;

  /**
   * Required and optional block signatures
   *
   * @generated from field: blockparty.v1.Signatures sigs = 7;
   */
  sigs?: Signatures | undefined;
};

/**
 * Describes the message blockparty.v1.Block.
 * Use `create(BlockSchema)` to create a new message.
 */
export const BlockSchema: GenMessage<Block> = /*@__PURE__*/
  messageDesc(file_block, 0);

/**
 * Signature bundle for a block
 *
 * @generated from message blockparty.v1.Signatures
 */
export type Signatures = Message<"blockparty.v1.Signatures"> & {
  /**
   * Signature from the World key
   *
   * @generated from field: bytes world = 1;
   */
  world: Uint8Array;

  /**
   * Signature from the author's root signing key
   *
   * @generated from field: bytes author = 2;
   */
  author: Uint8Array;

  /**
   * Optional additional signatures
   *
   * @generated from field: repeated blockparty.v1.ExtraSignature extra = 3;
   */
  extra: ExtraSignature[];
};

/**
 * Describes the message blockparty.v1.Signatures.
 * Use `create(SignaturesSchema)` to create a new message.
 */
export const SignaturesSchema: GenMessage<Signatures> = /*@__PURE__*/
  messageDesc(file_block, 1);

/**
 * Additional typed signature (e.g. endorsement, consensus, etc.)
 *
 * @generated from message blockparty.v1.ExtraSignature
 */
export type ExtraSignature = Message<"blockparty.v1.ExtraSignature"> & {
  /**
   * Type string (e.g. "com.example/endorse")
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * Signature bytes
   *
   * @generated from field: bytes sig = 2;
   */
  sig: Uint8Array;
};

/**
 * Describes the message blockparty.v1.ExtraSignature.
 * Use `create(ExtraSignatureSchema)` to create a new message.
 */
export const ExtraSignatureSchema: GenMessage<ExtraSignature> = /*@__PURE__*/
  messageDesc(file_block, 2);

