import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { bytesToHex, hexToBytes, utf8ToBytes } from "@noble/hashes/utils.js";
import {
  keccak256,
  sha256,
  sha512,
  hmacSha256,
  hkdfSha256,
  deterministicRNG,
  makeKyberPair,
  makeMldsaPair,
  signMldsa,
  verifyMldsa,
  encapsulate,
  decapsulate,
} from "./index.js";

// The shared cross-client conformance vectors, generated by the Go reference.
// This couples the JS SDK to the repo layout on purpose: it is the oracle that
// proves the two implementations interoperate.
const vectors = JSON.parse(
  readFileSync(
    fileURLToPath(new URL("../../../../../../conformance/vectors.json", import.meta.url)),
    "utf8",
  ),
) as {
  crypto: { seed: string; kyberPubKeccak: string; mldsaPubKeccak: string };
};

const hex = (b: Uint8Array) => bytesToHex(b);

describe("hash known-answer tests", () => {
  it("keccak256", () => {
    expect(hex(keccak256(utf8ToBytes("")))).toBe(
      "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
    );
    expect(hex(keccak256(utf8ToBytes("abc")))).toBe(
      "4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45",
    );
  });

  it("keccak256 concatenates parts", () => {
    expect(hex(keccak256(utf8ToBytes("foo"), utf8ToBytes("bar")))).toBe(
      hex(keccak256(utf8ToBytes("foobar"))),
    );
  });

  it("sha256 / sha512 empty", () => {
    expect(hex(sha256(utf8ToBytes("")))).toBe(
      "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    );
    expect(hex(sha512(utf8ToBytes("")))).toBe(
      "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
    );
  });

  it("HMAC-SHA256 (RFC 4231 #1)", () => {
    const key = new Uint8Array(20).fill(0x0b);
    expect(hex(hmacSha256(key, utf8ToBytes("Hi There")))).toBe(
      "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7",
    );
  });

  it("HKDF-SHA256 (RFC 5869 #1)", () => {
    const ikm = new Uint8Array(22).fill(0x0b);
    const salt = hexToBytes("000102030405060708090a0b0c");
    const info = hexToBytes("f0f1f2f3f4f5f6f7f8f9");
    expect(hex(hkdfSha256(ikm, salt, info, 42))).toBe(
      "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865",
    );
  });
});

describe("deterministic RNG", () => {
  it("is reproducible and stream-prefixed", () => {
    const a = deterministicRNG(utf8ToBytes("seed"), 128);
    const b = deterministicRNG(utf8ToBytes("seed"), 128);
    expect(hex(a)).toBe(hex(b));
    // dkLen=32 is the first 32 bytes of dkLen=64.
    expect(hex(deterministicRNG(utf8ToBytes("seed"), 32))).toBe(hex(a.subarray(0, 32)));
  });
});

describe("key generation", () => {
  const seed = utf8ToBytes(vectors.crypto.seed);

  it("is deterministic", () => {
    expect(hex(makeKyberPair(seed).publicKey)).toBe(hex(makeKyberPair(seed).publicKey));
    expect(hex(makeMldsaPair(seed).publicKey)).toBe(hex(makeMldsaPair(seed).publicKey));
  });

  it("matches the shared conformance vectors (cross-client parity with Go)", () => {
    expect(hex(keccak256(makeKyberPair(seed).publicKey))).toBe(vectors.crypto.kyberPubKeccak);
    expect(hex(keccak256(makeMldsaPair(seed).publicKey))).toBe(vectors.crypto.mldsaPubKeccak);
  });

  it("different seeds yield different keys", () => {
    expect(hex(makeKyberPair(utf8ToBytes("a")).publicKey)).not.toBe(
      hex(makeKyberPair(utf8ToBytes("b")).publicKey),
    );
  });
});

describe("ML-DSA-65 signatures", () => {
  const kp = makeMldsaPair(utf8ToBytes("signer"));
  const msg = utf8ToBytes("nothing can stop the signal");

  it("signs deterministically and verifies", () => {
    const sig = signMldsa(kp.secretKey, msg);
    expect(hex(sig)).toBe(hex(signMldsa(kp.secretKey, msg)));
    expect(verifyMldsa(kp.publicKey, msg, sig)).toBe(true);
  });

  it("rejects tampered message, signature, and wrong key", () => {
    const sig = signMldsa(kp.secretKey, msg);
    expect(verifyMldsa(kp.publicKey, utf8ToBytes("tampered"), sig)).toBe(false);
    const bad = sig.slice();
    bad[0] ^= 0xff;
    expect(verifyMldsa(kp.publicKey, msg, bad)).toBe(false);
    const other = makeMldsaPair(utf8ToBytes("other"));
    expect(verifyMldsa(other.publicKey, msg, sig)).toBe(false);
  });
});

describe("ML-KEM768 encapsulation", () => {
  it("round-trips a shared secret", () => {
    const kp = makeKyberPair(utf8ToBytes("kem"));
    const { ciphertext, sharedSecret } = encapsulate(kp.publicKey);
    expect(hex(decapsulate(ciphertext, kp.secretKey))).toBe(hex(sharedSecret));
    expect(sharedSecret.length).toBe(32);
  });

  it("wrong key decapsulates to a different secret (implicit rejection)", () => {
    const a = makeKyberPair(utf8ToBytes("a"));
    const b = makeKyberPair(utf8ToBytes("b"));
    const { ciphertext, sharedSecret } = encapsulate(a.publicKey);
    expect(hex(decapsulate(ciphertext, b.secretKey))).not.toBe(hex(sharedSecret));
  });
});
