// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: block_types.proto

package blockpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentPost) Reset() {
	*x = ContentPost{}
	mi := &file_block_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPost) ProtoMessage() {}

func (x *ContentPost) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPost.ProtoReflect.Descriptor instead.
func (*ContentPost) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{0}
}

func (x *ContentPost) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ContentPost) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ContentReaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Reaction      string                 `protobuf:"bytes,2,opt,name=reaction,proto3" json:"reaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentReaction) Reset() {
	*x = ContentReaction{}
	mi := &file_block_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentReaction) ProtoMessage() {}

func (x *ContentReaction) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentReaction.ProtoReflect.Descriptor instead.
func (*ContentReaction) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{1}
}

func (x *ContentReaction) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ContentReaction) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

type ContentTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentTagRequest) Reset() {
	*x = ContentTagRequest{}
	mi := &file_block_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentTagRequest) ProtoMessage() {}

func (x *ContentTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentTagRequest.ProtoReflect.Descriptor instead.
func (*ContentTagRequest) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{2}
}

func (x *ContentTagRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ContentTagRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ContentTagRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ContentTagAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentTagAccept) Reset() {
	*x = ContentTagAccept{}
	mi := &file_block_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentTagAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentTagAccept) ProtoMessage() {}

func (x *ContentTagAccept) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentTagAccept.ProtoReflect.Descriptor instead.
func (*ContentTagAccept) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{3}
}

func (x *ContentTagAccept) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type ContentChunkedManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Chunks        []string               `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Sha512        string                 `protobuf:"bytes,3,opt,name=sha512,proto3" json:"sha512,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentChunkedManifest) Reset() {
	*x = ContentChunkedManifest{}
	mi := &file_block_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentChunkedManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentChunkedManifest) ProtoMessage() {}

func (x *ContentChunkedManifest) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentChunkedManifest.ProtoReflect.Descriptor instead.
func (*ContentChunkedManifest) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{4}
}

func (x *ContentChunkedManifest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ContentChunkedManifest) GetChunks() []string {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ContentChunkedManifest) GetSha512() string {
	if x != nil {
		return x.Sha512
	}
	return ""
}

type ContentChunkedBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentChunkedBlock) Reset() {
	*x = ContentChunkedBlock{}
	mi := &file_block_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentChunkedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentChunkedBlock) ProtoMessage() {}

func (x *ContentChunkedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentChunkedBlock.ProtoReflect.Descriptor instead.
func (*ContentChunkedBlock) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{5}
}

func (x *ContentChunkedBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ContentGallery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Blocks        []string               `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentGallery) Reset() {
	*x = ContentGallery{}
	mi := &file_block_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentGallery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentGallery) ProtoMessage() {}

func (x *ContentGallery) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentGallery.ProtoReflect.Descriptor instead.
func (*ContentGallery) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{6}
}

func (x *ContentGallery) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentGallery) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ContentGallery) GetBlocks() []string {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type ContentQuote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quote         string                 `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	Commentary    *ContentPost           `protobuf:"bytes,2,opt,name=commentary,proto3,oneof" json:"commentary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentQuote) Reset() {
	*x = ContentQuote{}
	mi := &file_block_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentQuote) ProtoMessage() {}

func (x *ContentQuote) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentQuote.ProtoReflect.Descriptor instead.
func (*ContentQuote) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{7}
}

func (x *ContentQuote) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *ContentQuote) GetCommentary() *ContentPost {
	if x != nil {
		return x.Commentary
	}
	return nil
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`                                    // target identity address
	InitKemPub    []byte                 `protobuf:"bytes,2,opt,name=init_kem_pub,json=initKemPub,proto3" json:"init_kem_pub,omitempty"`        // initiator's ephemeral ML-KEM768 public key
	KemCiphertext []byte                 `protobuf:"bytes,3,opt,name=kem_ciphertext,json=kemCiphertext,proto3" json:"kem_ciphertext,omitempty"` // ML-KEM768 ciphertext encapsulated to target's static kyber key
	Nonce         []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`                                      // 32 random bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_block_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ConnectRequest) GetInitKemPub() []byte {
	if x != nil {
		return x.InitKemPub
	}
	return nil
}

func (x *ConnectRequest) GetKemCiphertext() []byte {
	if x != nil {
		return x.KemCiphertext
	}
	return nil
}

func (x *ConnectRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`                                  // connect.request block id
	KemCiphertext []byte                 `protobuf:"bytes,2,opt,name=kem_ciphertext,json=kemCiphertext,proto3" json:"kem_ciphertext,omitempty"` // ML-KEM768 ciphertext encapsulated to initiator's init_kem_pub
	NonceResponse []byte                 `protobuf:"bytes,3,opt,name=nonce_response,json=nonceResponse,proto3" json:"nonce_response,omitempty"` // 32 random bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_block_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectResponse) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *ConnectResponse) GetKemCiphertext() []byte {
	if x != nil {
		return x.KemCiphertext
	}
	return nil
}

func (x *ConnectResponse) GetNonceResponse() []byte {
	if x != nil {
		return x.NonceResponse
	}
	return nil
}

type ConnectIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"` // additional public keys shared within the connection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectIdentity) Reset() {
	*x = ConnectIdentity{}
	mi := &file_block_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectIdentity) ProtoMessage() {}

func (x *ConnectIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectIdentity.ProtoReflect.Descriptor instead.
func (*ConnectIdentity) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectIdentity) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ConnectRotate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewChannel    string                 `protobuf:"bytes,1,opt,name=new_channel,json=newChannel,proto3" json:"new_channel,omitempty"`          // hex audience_code of the next epoch
	KemCiphertext []byte                 `protobuf:"bytes,2,opt,name=kem_ciphertext,json=kemCiphertext,proto3" json:"kem_ciphertext,omitempty"` // fresh ML-KEM768 contribution (forward ratchet)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRotate) Reset() {
	*x = ConnectRotate{}
	mi := &file_block_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRotate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRotate) ProtoMessage() {}

func (x *ConnectRotate) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRotate.ProtoReflect.Descriptor instead.
func (*ConnectRotate) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectRotate) GetNewChannel() string {
	if x != nil {
		return x.NewChannel
	}
	return ""
}

func (x *ConnectRotate) GetKemCiphertext() []byte {
	if x != nil {
		return x.KemCiphertext
	}
	return nil
}

type ConnectClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectClose) Reset() {
	*x = ConnectClose{}
	mi := &file_block_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectClose) ProtoMessage() {}

func (x *ConnectClose) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectClose.ProtoReflect.Descriptor instead.
func (*ConnectClose) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{12}
}

func (x *ConnectClose) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ConnectClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type IdentityDeclare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKeys    []string               `protobuf:"bytes,2,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityDeclare) Reset() {
	*x = IdentityDeclare{}
	mi := &file_block_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityDeclare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityDeclare) ProtoMessage() {}

func (x *IdentityDeclare) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityDeclare.ProtoReflect.Descriptor instead.
func (*IdentityDeclare) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{13}
}

func (x *IdentityDeclare) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdentityDeclare) GetPublicKeys() []string {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type IdentityBurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`                                  // address of the identity being burned
	RevealedMlDsa []byte                 `protobuf:"bytes,2,opt,name=revealed_ml_dsa,json=revealedMlDsa,proto3" json:"revealed_ml_dsa,omitempty"` // revealed root ML-DSA-65 private key
	RevealedKyber []byte                 `protobuf:"bytes,3,opt,name=revealed_kyber,json=revealedKyber,proto3" json:"revealed_kyber,omitempty"`   // revealed root ML-KEM768 private key
	BurnNotice    string                 `protobuf:"bytes,4,opt,name=burn_notice,json=burnNotice,proto3" json:"burn_notice,omitempty"`            // "voluntary" | "compromised" | "rotated" | "other"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityBurn) Reset() {
	*x = IdentityBurn{}
	mi := &file_block_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityBurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityBurn) ProtoMessage() {}

func (x *IdentityBurn) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityBurn.ProtoReflect.Descriptor instead.
func (*IdentityBurn) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{14}
}

func (x *IdentityBurn) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *IdentityBurn) GetRevealedMlDsa() []byte {
	if x != nil {
		return x.RevealedMlDsa
	}
	return nil
}

func (x *IdentityBurn) GetRevealedKyber() []byte {
	if x != nil {
		return x.RevealedKyber
	}
	return nil
}

func (x *IdentityBurn) GetBurnNotice() string {
	if x != nil {
		return x.BurnNotice
	}
	return ""
}

type ChunkManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []string               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Sha512        string                 `protobuf:"bytes,2,opt,name=sha512,proto3" json:"sha512,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkManifest) Reset() {
	*x = ChunkManifest{}
	mi := &file_block_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkManifest) ProtoMessage() {}

func (x *ChunkManifest) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkManifest.ProtoReflect.Descriptor instead.
func (*ChunkManifest) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{15}
}

func (x *ChunkManifest) GetChunks() []string {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ChunkManifest) GetSha512() string {
	if x != nil {
		return x.Sha512
	}
	return ""
}

type ChunkBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkBlock) Reset() {
	*x = ChunkBlock{}
	mi := &file_block_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkBlock) ProtoMessage() {}

func (x *ChunkBlock) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkBlock.ProtoReflect.Descriptor instead.
func (*ChunkBlock) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{16}
}

func (x *ChunkBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_block_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{17}
}

func (x *RpcRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RpcRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        map[string]string      `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_block_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{18}
}

func (x *RpcResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcResponse) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RpcResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RpcRender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRender) Reset() {
	*x = RpcRender{}
	mi := &file_block_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRender) ProtoMessage() {}

func (x *RpcRender) ProtoReflect() protoreflect.Message {
	mi := &file_block_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRender.ProtoReflect.Descriptor instead.
func (*RpcRender) Descriptor() ([]byte, []int) {
	return file_block_types_proto_rawDescGZIP(), []int{19}
}

func (x *RpcRender) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcRender) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RpcRender) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_block_types_proto protoreflect.FileDescriptor

const file_block_types_proto_rawDesc = "" +
	"\n" +
	"\x11block_types.proto\x12\rblockparty.v1\"\xa0\x01\n" +
	"\vContentPost\x12A\n" +
	"\aheaders\x18\x01 \x03(\v2'.blockparty.v1.ContentPost.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x0fContentReaction\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1a\n" +
	"\breaction\x18\x02 \x01(\tR\breaction\"]\n" +
	"\x11ContentTagRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\",\n" +
	"\x10ContentTagAccept\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\"\xd2\x01\n" +
	"\x16ContentChunkedManifest\x12L\n" +
	"\aheaders\x18\x01 \x03(\v22.blockparty.v1.ContentChunkedManifest.HeadersEntryR\aheaders\x12\x16\n" +
	"\x06chunks\x18\x02 \x03(\tR\x06chunks\x12\x16\n" +
	"\x06sha512\x18\x03 \x01(\tR\x06sha512\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x13ContentChunkedBlock\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"`\n" +
	"\x0eContentGallery\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06blocks\x18\x03 \x03(\tR\x06blocks\"t\n" +
	"\fContentQuote\x12\x14\n" +
	"\x05quote\x18\x01 \x01(\tR\x05quote\x12?\n" +
	"\n" +
	"commentary\x18\x02 \x01(\v2\x1a.blockparty.v1.ContentPostH\x00R\n" +
	"commentary\x88\x01\x01B\r\n" +
	"\v_commentary\"\x87\x01\n" +
	"\x0eConnectRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12 \n" +
	"\finit_kem_pub\x18\x02 \x01(\fR\n" +
	"initKemPub\x12%\n" +
	"\x0ekem_ciphertext\x18\x03 \x01(\fR\rkemCiphertext\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\"y\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\x12%\n" +
	"\x0ekem_ciphertext\x18\x02 \x01(\fR\rkemCiphertext\x12%\n" +
	"\x0enonce_response\x18\x03 \x01(\fR\rnonceResponse\"9\n" +
	"\x0fConnectIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"W\n" +
	"\rConnectRotate\x12\x1f\n" +
	"\vnew_channel\x18\x01 \x01(\tR\n" +
	"newChannel\x12%\n" +
	"\x0ekem_ciphertext\x18\x02 \x01(\fR\rkemCiphertext\">\n" +
	"\fConnectClose\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"F\n" +
	"\x0fIdentityDeclare\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vpublic_keys\x18\x02 \x03(\tR\n" +
	"publicKeys\"\x9a\x01\n" +
	"\fIdentityBurn\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12&\n" +
	"\x0frevealed_ml_dsa\x18\x02 \x01(\fR\rrevealedMlDsa\x12%\n" +
	"\x0erevealed_kyber\x18\x03 \x01(\fR\rrevealedKyber\x12\x1f\n" +
	"\vburn_notice\x18\x04 \x01(\tR\n" +
	"burnNotice\"?\n" +
	"\rChunkManifest\x12\x16\n" +
	"\x06chunks\x18\x01 \x03(\tR\x06chunks\x12\x16\n" +
	"\x06sha512\x18\x02 \x01(\tR\x06sha512\" \n" +
	"\n" +
	"ChunkBlock\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xae\x01\n" +
	"\n" +
	"RpcRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12=\n" +
	"\x06params\x18\x03 \x03(\v2%.blockparty.v1.RpcRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\vRpcResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\x06result\x18\x02 \x03(\v2&.blockparty.v1.RpcResponse.ResultEntryR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\tRpcRender\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12<\n" +
	"\x06params\x18\x03 \x03(\v2$.blockparty.v1.RpcRender.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B6Z4github.com/bpprotocol/blockparty/sdk/blockpb;blockpbb\x06proto3"

var (
	file_block_types_proto_rawDescOnce sync.Once
	file_block_types_proto_rawDescData []byte
)

func file_block_types_proto_rawDescGZIP() []byte {
	file_block_types_proto_rawDescOnce.Do(func() {
		file_block_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_types_proto_rawDesc), len(file_block_types_proto_rawDesc)))
	})
	return file_block_types_proto_rawDescData
}

var file_block_types_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_block_types_proto_goTypes = []any{
	(*ContentPost)(nil),            // 0: blockparty.v1.ContentPost
	(*ContentReaction)(nil),        // 1: blockparty.v1.ContentReaction
	(*ContentTagRequest)(nil),      // 2: blockparty.v1.ContentTagRequest
	(*ContentTagAccept)(nil),       // 3: blockparty.v1.ContentTagAccept
	(*ContentChunkedManifest)(nil), // 4: blockparty.v1.ContentChunkedManifest
	(*ContentChunkedBlock)(nil),    // 5: blockparty.v1.ContentChunkedBlock
	(*ContentGallery)(nil),         // 6: blockparty.v1.ContentGallery
	(*ContentQuote)(nil),           // 7: blockparty.v1.ContentQuote
	(*ConnectRequest)(nil),         // 8: blockparty.v1.ConnectRequest
	(*ConnectResponse)(nil),        // 9: blockparty.v1.ConnectResponse
	(*ConnectIdentity)(nil),        // 10: blockparty.v1.ConnectIdentity
	(*ConnectRotate)(nil),          // 11: blockparty.v1.ConnectRotate
	(*ConnectClose)(nil),           // 12: blockparty.v1.ConnectClose
	(*IdentityDeclare)(nil),        // 13: blockparty.v1.IdentityDeclare
	(*IdentityBurn)(nil),           // 14: blockparty.v1.IdentityBurn
	(*ChunkManifest)(nil),          // 15: blockparty.v1.ChunkManifest
	(*ChunkBlock)(nil),             // 16: blockparty.v1.ChunkBlock
	(*RpcRequest)(nil),             // 17: blockparty.v1.RpcRequest
	(*RpcResponse)(nil),            // 18: blockparty.v1.RpcResponse
	(*RpcRender)(nil),              // 19: blockparty.v1.RpcRender
	nil,                            // 20: blockparty.v1.ContentPost.HeadersEntry
	nil,                            // 21: blockparty.v1.ContentChunkedManifest.HeadersEntry
	nil,                            // 22: blockparty.v1.RpcRequest.ParamsEntry
	nil,                            // 23: blockparty.v1.RpcResponse.ResultEntry
	nil,                            // 24: blockparty.v1.RpcRender.ParamsEntry
}
var file_block_types_proto_depIdxs = []int32{
	20, // 0: blockparty.v1.ContentPost.headers:type_name -> blockparty.v1.ContentPost.HeadersEntry
	21, // 1: blockparty.v1.ContentChunkedManifest.headers:type_name -> blockparty.v1.ContentChunkedManifest.HeadersEntry
	0,  // 2: blockparty.v1.ContentQuote.commentary:type_name -> blockparty.v1.ContentPost
	22, // 3: blockparty.v1.RpcRequest.params:type_name -> blockparty.v1.RpcRequest.ParamsEntry
	23, // 4: blockparty.v1.RpcResponse.result:type_name -> blockparty.v1.RpcResponse.ResultEntry
	24, // 5: blockparty.v1.RpcRender.params:type_name -> blockparty.v1.RpcRender.ParamsEntry
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_block_types_proto_init() }
func file_block_types_proto_init() {
	if File_block_types_proto != nil {
		return
	}
	file_block_types_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_types_proto_rawDesc), len(file_block_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_types_proto_goTypes,
		DependencyIndexes: file_block_types_proto_depIdxs,
		MessageInfos:      file_block_types_proto_msgTypes,
	}.Build()
	File_block_types_proto = out.File
	file_block_types_proto_goTypes = nil
	file_block_types_proto_depIdxs = nil
}
