// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: block.proto

package blockpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Canonical BlockParty block format
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                              // Block version (e.g. 1)
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                         // Derived block ID (optional precomputed or recomputed)
	TypeCode      []byte                 `protobuf:"bytes,3,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`             // World-scoped type hash
	AudienceCode  []byte                 `protobuf:"bytes,4,opt,name=audience_code,json=audienceCode,proto3" json:"audience_code,omitempty"` // World-scoped audience hash
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // Unix timestamp (seconds since epoch)
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                     // Encrypted or plaintext payload
	Sigs          *Signatures            `protobuf:"bytes,7,opt,name=sigs,proto3" json:"sigs,omitempty"`                                     // Required and optional block signatures
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Block) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Block) GetTypeCode() []byte {
	if x != nil {
		return x.TypeCode
	}
	return nil
}

func (x *Block) GetAudienceCode() []byte {
	if x != nil {
		return x.AudienceCode
	}
	return nil
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Block) GetSigs() *Signatures {
	if x != nil {
		return x.Sigs
	}
	return nil
}

// Signature bundle for a block
type Signatures struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	World         []byte                 `protobuf:"bytes,1,opt,name=world,proto3" json:"world,omitempty"`   // Signature from the World key
	Author        []byte                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"` // Signature from the author's root signing key
	Extra         []*ExtraSignature      `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty"`   // Optional additional signatures
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signatures) Reset() {
	*x = Signatures{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signatures) ProtoMessage() {}

func (x *Signatures) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signatures.ProtoReflect.Descriptor instead.
func (*Signatures) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *Signatures) GetWorld() []byte {
	if x != nil {
		return x.World
	}
	return nil
}

func (x *Signatures) GetAuthor() []byte {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Signatures) GetExtra() []*ExtraSignature {
	if x != nil {
		return x.Extra
	}
	return nil
}

// Additional typed signature (e.g. endorsement, consensus, etc.)
type ExtraSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Type string (e.g. "com.example/endorse")
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`   // Signature bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraSignature) Reset() {
	*x = ExtraSignature{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraSignature) ProtoMessage() {}

func (x *ExtraSignature) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraSignature.ProtoReflect.Descriptor instead.
func (*ExtraSignature) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *ExtraSignature) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExtraSignature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\rblockparty.v1\"\xd4\x01\n" +
	"\x05Block\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x1b\n" +
	"\ttype_code\x18\x03 \x01(\fR\btypeCode\x12#\n" +
	"\raudience_code\x18\x04 \x01(\fR\faudienceCode\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12-\n" +
	"\x04sigs\x18\a \x01(\v2\x19.blockparty.v1.SignaturesR\x04sigs\"o\n" +
	"\n" +
	"Signatures\x12\x14\n" +
	"\x05world\x18\x01 \x01(\fR\x05world\x12\x16\n" +
	"\x06author\x18\x02 \x01(\fR\x06author\x123\n" +
	"\x05extra\x18\x03 \x03(\v2\x1d.blockparty.v1.ExtraSignatureR\x05extra\"6\n" +
	"\x0eExtraSignature\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sigBEZCgithub.com/bpprotocol/blockparty/implementations/go/blockpb;blockpbb\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_block_proto_goTypes = []any{
	(*Block)(nil),          // 0: blockparty.v1.Block
	(*Signatures)(nil),     // 1: blockparty.v1.Signatures
	(*ExtraSignature)(nil), // 2: blockparty.v1.ExtraSignature
}
var file_block_proto_depIdxs = []int32{
	1, // 0: blockparty.v1.Block.sigs:type_name -> blockparty.v1.Signatures
	2, // 1: blockparty.v1.Signatures.extra:type_name -> blockparty.v1.ExtraSignature
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
