// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: node.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // "personal" | "relay"
	WorldLoaded   bool                   `protobuf:"varint,3,opt,name=world_loaded,json=worldLoaded,proto3" json:"world_loaded,omitempty"`
	World         string                 `protobuf:"bytes,4,opt,name=world,proto3" json:"world,omitempty"`       // World fingerprint when loaded
	Identity      string                 `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"` // identity address (personal, keystore unlocked)
	BlockCount    int64                  `protobuf:"varint,6,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	CanAuthor     bool                   `protobuf:"varint,7,opt,name=can_author,json=canAuthor,proto3" json:"can_author,omitempty"` // node holds an unlocked keystore
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetStatusResponse) GetWorldLoaded() bool {
	if x != nil {
		return x.WorldLoaded
	}
	return false
}

func (x *GetStatusResponse) GetWorld() string {
	if x != nil {
		return x.World
	}
	return ""
}

func (x *GetStatusResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetStatusResponse) GetBlockCount() int64 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *GetStatusResponse) GetCanAuthor() bool {
	if x != nil {
		return x.CanAuthor
	}
	return false
}

type BootstrapWorldRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorldSeed          string                 `protobuf:"bytes,1,opt,name=world_seed,json=worldSeed,proto3" json:"world_seed,omitempty"`                            // secret: the World seed phrase
	IdentityPassphrase string                 `protobuf:"bytes,2,opt,name=identity_passphrase,json=identityPassphrase,proto3" json:"identity_passphrase,omitempty"` // secret: seeds the identity
	KeystorePassphrase string                 `protobuf:"bytes,3,opt,name=keystore_passphrase,json=keystorePassphrase,proto3" json:"keystore_passphrase,omitempty"` // secret: unlocks the new encrypted keystore
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BootstrapWorldRequest) Reset() {
	*x = BootstrapWorldRequest{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapWorldRequest) ProtoMessage() {}

func (x *BootstrapWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapWorldRequest.ProtoReflect.Descriptor instead.
func (*BootstrapWorldRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *BootstrapWorldRequest) GetWorldSeed() string {
	if x != nil {
		return x.WorldSeed
	}
	return ""
}

func (x *BootstrapWorldRequest) GetIdentityPassphrase() string {
	if x != nil {
		return x.IdentityPassphrase
	}
	return ""
}

func (x *BootstrapWorldRequest) GetKeystorePassphrase() string {
	if x != nil {
		return x.KeystorePassphrase
	}
	return ""
}

type BootstrapWorldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	World         string                 `protobuf:"bytes,1,opt,name=world,proto3" json:"world,omitempty"`       // World fingerprint
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"` // identity address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapWorldResponse) Reset() {
	*x = BootstrapWorldResponse{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapWorldResponse) ProtoMessage() {}

func (x *BootstrapWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapWorldResponse.ProtoReflect.Descriptor instead.
func (*BootstrapWorldResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *BootstrapWorldResponse) GetWorld() string {
	if x != nil {
		return x.World
	}
	return ""
}

func (x *BootstrapWorldResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type PostTextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PublicAudience uint32                 `protobuf:"varint,1,opt,name=public_audience,json=publicAudience,proto3" json:"public_audience,omitempty"` // public-N (1..16)
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostTextRequest) Reset() {
	*x = PostTextRequest{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTextRequest) ProtoMessage() {}

func (x *PostTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTextRequest.ProtoReflect.Descriptor instead.
func (*PostTextRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *PostTextRequest) GetPublicAudience() uint32 {
	if x != nil {
		return x.PublicAudience
	}
	return 0
}

func (x *PostTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PostTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // block ID, hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTextResponse) Reset() {
	*x = PostTextResponse{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTextResponse) ProtoMessage() {}

func (x *PostTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTextResponse.ProtoReflect.Descriptor instead.
func (*PostTextResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *PostTextResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// BlockSummary is the index view of a stored block (no payload).
type BlockSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AudienceCode  string                 `protobuf:"bytes,2,opt,name=audience_code,json=audienceCode,proto3" json:"audience_code,omitempty"` // hex
	TypeCode      string                 `protobuf:"bytes,3,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`             // hex
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`                                 // hex address ("" if unresolved)
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReceivedAt    int64                  `protobuf:"varint,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSummary) Reset() {
	*x = BlockSummary{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSummary) ProtoMessage() {}

func (x *BlockSummary) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSummary.ProtoReflect.Descriptor instead.
func (*BlockSummary) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *BlockSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockSummary) GetAudienceCode() string {
	if x != nil {
		return x.AudienceCode
	}
	return ""
}

func (x *BlockSummary) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *BlockSummary) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BlockSummary) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockSummary) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *BlockSummary          `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`            // block.data (plaintext if decrypted, else ciphertext)
	Decrypted     bool                   `protobuf:"varint,3,opt,name=decrypted,proto3" json:"decrypted,omitempty"` // node opened the payload
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`            // content.post body, when decrypted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *GetBlockResponse) GetSummary() *BlockSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetBlockResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBlockResponse) GetDecrypted() bool {
	if x != nil {
		return x.Decrypted
	}
	return false
}

func (x *GetBlockResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ListBlocksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provide exactly one filter: an audience/type/author exact match, or a time
	// range (from..to inclusive; to=0 means open-ended).
	AudienceCode  string `protobuf:"bytes,1,opt,name=audience_code,json=audienceCode,proto3" json:"audience_code,omitempty"` // hex
	TypeCode      string `protobuf:"bytes,2,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`             // hex
	Author        string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`                                 // hex
	From          int64  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	To            int64  `protobuf:"varint,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksRequest) Reset() {
	*x = ListBlocksRequest{}
	mi := &file_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksRequest) ProtoMessage() {}

func (x *ListBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListBlocksRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{9}
}

func (x *ListBlocksRequest) GetAudienceCode() string {
	if x != nil {
		return x.AudienceCode
	}
	return ""
}

func (x *ListBlocksRequest) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *ListBlocksRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ListBlocksRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ListBlocksRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type ListBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockSummary        `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksResponse) Reset() {
	*x = ListBlocksResponse{}
	mi := &file_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksResponse) ProtoMessage() {}

func (x *ListBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksResponse.ProtoReflect.Descriptor instead.
func (*ListBlocksResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{10}
}

func (x *ListBlocksResponse) GetBlocks() []*BlockSummary {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type SubscribeBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudienceCode  string                 `protobuf:"bytes,1,opt,name=audience_code,json=audienceCode,proto3" json:"audience_code,omitempty"` // hex; empty = all audiences the node follows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeBlocksRequest) Reset() {
	*x = SubscribeBlocksRequest{}
	mi := &file_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeBlocksRequest) ProtoMessage() {}

func (x *SubscribeBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeBlocksRequest.ProtoReflect.Descriptor instead.
func (*SubscribeBlocksRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeBlocksRequest) GetAudienceCode() string {
	if x != nil {
		return x.AudienceCode
	}
	return ""
}

type BlockEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *BlockSummary          `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockEvent) Reset() {
	*x = BlockEvent{}
	mi := &file_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEvent) ProtoMessage() {}

func (x *BlockEvent) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEvent.ProtoReflect.Descriptor instead.
func (*BlockEvent) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{12}
}

func (x *BlockEvent) GetSummary() *BlockSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x12blockparty.node.v1\"\x12\n" +
	"\x10GetStatusRequest\"\xd6\x01\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12!\n" +
	"\fworld_loaded\x18\x03 \x01(\bR\vworldLoaded\x12\x14\n" +
	"\x05world\x18\x04 \x01(\tR\x05world\x12\x1a\n" +
	"\bidentity\x18\x05 \x01(\tR\bidentity\x12\x1f\n" +
	"\vblock_count\x18\x06 \x01(\x03R\n" +
	"blockCount\x12\x1d\n" +
	"\n" +
	"can_author\x18\a \x01(\bR\tcanAuthor\"\x98\x01\n" +
	"\x15BootstrapWorldRequest\x12\x1d\n" +
	"\n" +
	"world_seed\x18\x01 \x01(\tR\tworldSeed\x12/\n" +
	"\x13identity_passphrase\x18\x02 \x01(\tR\x12identityPassphrase\x12/\n" +
	"\x13keystore_passphrase\x18\x03 \x01(\tR\x12keystorePassphrase\"J\n" +
	"\x16BootstrapWorldResponse\x12\x14\n" +
	"\x05world\x18\x01 \x01(\tR\x05world\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\"N\n" +
	"\x0fPostTextRequest\x12'\n" +
	"\x0fpublic_audience\x18\x01 \x01(\rR\x0epublicAudience\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\"\n" +
	"\x10PostTextResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb7\x01\n" +
	"\fBlockSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\raudience_code\x18\x02 \x01(\tR\faudienceCode\x12\x1b\n" +
	"\ttype_code\x18\x03 \x01(\tR\btypeCode\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vreceived_at\x18\x06 \x01(\x03R\n" +
	"receivedAt\"!\n" +
	"\x0fGetBlockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x94\x01\n" +
	"\x10GetBlockResponse\x12:\n" +
	"\asummary\x18\x01 \x01(\v2 .blockparty.node.v1.BlockSummaryR\asummary\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\tdecrypted\x18\x03 \x01(\bR\tdecrypted\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\x91\x01\n" +
	"\x11ListBlocksRequest\x12#\n" +
	"\raudience_code\x18\x01 \x01(\tR\faudienceCode\x12\x1b\n" +
	"\ttype_code\x18\x02 \x01(\tR\btypeCode\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\x03R\x02to\"N\n" +
	"\x12ListBlocksResponse\x128\n" +
	"\x06blocks\x18\x01 \x03(\v2 .blockparty.node.v1.BlockSummaryR\x06blocks\"=\n" +
	"\x16SubscribeBlocksRequest\x12#\n" +
	"\raudience_code\x18\x01 \x01(\tR\faudienceCode\"H\n" +
	"\n" +
	"BlockEvent\x12:\n" +
	"\asummary\x18\x01 \x01(\v2 .blockparty.node.v1.BlockSummaryR\asummary2\xbc\x04\n" +
	"\vNodeService\x12X\n" +
	"\tGetStatus\x12$.blockparty.node.v1.GetStatusRequest\x1a%.blockparty.node.v1.GetStatusResponse\x12g\n" +
	"\x0eBootstrapWorld\x12).blockparty.node.v1.BootstrapWorldRequest\x1a*.blockparty.node.v1.BootstrapWorldResponse\x12U\n" +
	"\bPostText\x12#.blockparty.node.v1.PostTextRequest\x1a$.blockparty.node.v1.PostTextResponse\x12U\n" +
	"\bGetBlock\x12#.blockparty.node.v1.GetBlockRequest\x1a$.blockparty.node.v1.GetBlockResponse\x12[\n" +
	"\n" +
	"ListBlocks\x12%.blockparty.node.v1.ListBlocksRequest\x1a&.blockparty.node.v1.ListBlocksResponse\x12_\n" +
	"\x0fSubscribeBlocks\x12*.blockparty.node.v1.SubscribeBlocksRequest\x1a\x1e.blockparty.node.v1.BlockEvent0\x01B>Z<github.com/bpprotocol/blockparty/node/internal/nodepb;nodepbb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_node_proto_goTypes = []any{
	(*GetStatusRequest)(nil),       // 0: blockparty.node.v1.GetStatusRequest
	(*GetStatusResponse)(nil),      // 1: blockparty.node.v1.GetStatusResponse
	(*BootstrapWorldRequest)(nil),  // 2: blockparty.node.v1.BootstrapWorldRequest
	(*BootstrapWorldResponse)(nil), // 3: blockparty.node.v1.BootstrapWorldResponse
	(*PostTextRequest)(nil),        // 4: blockparty.node.v1.PostTextRequest
	(*PostTextResponse)(nil),       // 5: blockparty.node.v1.PostTextResponse
	(*BlockSummary)(nil),           // 6: blockparty.node.v1.BlockSummary
	(*GetBlockRequest)(nil),        // 7: blockparty.node.v1.GetBlockRequest
	(*GetBlockResponse)(nil),       // 8: blockparty.node.v1.GetBlockResponse
	(*ListBlocksRequest)(nil),      // 9: blockparty.node.v1.ListBlocksRequest
	(*ListBlocksResponse)(nil),     // 10: blockparty.node.v1.ListBlocksResponse
	(*SubscribeBlocksRequest)(nil), // 11: blockparty.node.v1.SubscribeBlocksRequest
	(*BlockEvent)(nil),             // 12: blockparty.node.v1.BlockEvent
}
var file_node_proto_depIdxs = []int32{
	6,  // 0: blockparty.node.v1.GetBlockResponse.summary:type_name -> blockparty.node.v1.BlockSummary
	6,  // 1: blockparty.node.v1.ListBlocksResponse.blocks:type_name -> blockparty.node.v1.BlockSummary
	6,  // 2: blockparty.node.v1.BlockEvent.summary:type_name -> blockparty.node.v1.BlockSummary
	0,  // 3: blockparty.node.v1.NodeService.GetStatus:input_type -> blockparty.node.v1.GetStatusRequest
	2,  // 4: blockparty.node.v1.NodeService.BootstrapWorld:input_type -> blockparty.node.v1.BootstrapWorldRequest
	4,  // 5: blockparty.node.v1.NodeService.PostText:input_type -> blockparty.node.v1.PostTextRequest
	7,  // 6: blockparty.node.v1.NodeService.GetBlock:input_type -> blockparty.node.v1.GetBlockRequest
	9,  // 7: blockparty.node.v1.NodeService.ListBlocks:input_type -> blockparty.node.v1.ListBlocksRequest
	11, // 8: blockparty.node.v1.NodeService.SubscribeBlocks:input_type -> blockparty.node.v1.SubscribeBlocksRequest
	1,  // 9: blockparty.node.v1.NodeService.GetStatus:output_type -> blockparty.node.v1.GetStatusResponse
	3,  // 10: blockparty.node.v1.NodeService.BootstrapWorld:output_type -> blockparty.node.v1.BootstrapWorldResponse
	5,  // 11: blockparty.node.v1.NodeService.PostText:output_type -> blockparty.node.v1.PostTextResponse
	8,  // 12: blockparty.node.v1.NodeService.GetBlock:output_type -> blockparty.node.v1.GetBlockResponse
	10, // 13: blockparty.node.v1.NodeService.ListBlocks:output_type -> blockparty.node.v1.ListBlocksResponse
	12, // 14: blockparty.node.v1.NodeService.SubscribeBlocks:output_type -> blockparty.node.v1.BlockEvent
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
